#!/bin/bash
#SBATCH --account=sunwbgt0
#SBATCH --job-name=RL-AB-PG
#SBATCH --mail-user=xysong@umich.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --nodes=1
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --mem-per-gpu=16GB
#SBATCH --time=5:00:00
#SBATCH --output=/nfs/turbo/coe-sunwbgt/xysong/RL-AB-Triggering-Controller/checkpoints/logs/policy_gradient_train.log

# Submit with `conda activate RL && sbatch jobs/policy_gradient/train_pg.sh`
# from the repo root — matches jobs/sensitivity/j0.sh's convention of relying
# on the submitting shell's active env rather than activating one here.

# =========================
# Shared reward parameters
# (matches jobs/sensitivity/j0.sh — the "all 5.0" reward config)
# =========================
B1=5.0
C1=5.0
B2=5.0
C2=5.0
C3=5.0
ETA=0.15

# =========================
# Training
# =========================
NUM_EPOCHS=1000
ACTOR_LR=1e-3
CRITIC_LR=1e-3
HIDDEN_DIM=256
BATCH_SIZE=10000

# =========================
# Pipeline
# =========================
# Assumes data/aggregated/rl_trajectories_b1${B1}_c1${C1}_b2${B2}_c2${C2}_c3${C3}_eta${ETA}.pkl
# already exists (generated by data/transform_reward.py for the Q-learning run).

python policy_gradient/train.py \
    --b1 $B1 --c1 $C1 --b2 $B2 --c2 $C2 --c3 $C3 --eta $ETA \
    --num_epochs $NUM_EPOCHS --actor_lr $ACTOR_LR --critic_lr $CRITIC_LR \
    --hidden_dim $HIDDEN_DIM --batch_size $BATCH_SIZE

python policy_gradient/test.py \
    --b1 $B1 --c1 $C1 --b2 $B2 --c2 $C2 --c3 $C3 --eta $ETA
